[tool.poetry]
name = "pyhance-4"
version = "0.1.0"
description = ""
authors = ["IzaCoder <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
yapf = "^0.31.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
