name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for raising an issue! I really hope you're enjoying the software 😁"
        pr-message: "Thank you very, very much for contributing -- your work is greatly appreciated. 🤞 your request gets accepted!"
